apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-nodejs-deployment-prod
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-nodejs-prod
  template:
    metadata:
      labels:
        app: tcc-nodejs-prod
    spec:
      containers:
        - name: tcc-nodejs-prod
          image: thanapongsj/tcc-nodejs:release-3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: tcc-nodejs-configmap-prod
                  key: ENV_NAME
