apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-nodejs-deployment
  namespace: develop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcc-nodejs
  template:
    metadata:
      labels:
        app: tcc-nodejs
    spec:
      containers:
        - name: tcc-nodejs
          image: thanapongsj/tcc-nodejs:56ba452d81149642e3d82fc0c8e3c031be9e293a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: tcc-nodejs-configmap
                  key: ENV_NAME
