apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tcc-nodejs
  template:
    metadata:
      labels:
        app: tcc-nodejs
    spec:
      containers:
        - name: tcc-nodejs
          image: thanapongsj/tcc-nodejs:develop
          ports:
            - containerPort: 3000
