apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-nodejs
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-nodejs
  template:
    metadata:
      labels:
        app: tcc-nodejs
    spec:
      containers:
        - name: tcc-nodejs
          image: thanapongsj/tcc-nodejs:ac11b5bbd916ea12ebd337755afe12481550f0af
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: tcc-nodejs-configmap
                  key: ENV_NAME
